/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalleresRouteImport } from './routes/talleres'
import { Route as ProduccionesRouteImport } from './routes/producciones'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as FesmicaRouteImport } from './routes/fesmica'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const TalleresRoute = TalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionesRoute = ProduccionesRouteImport.update({
  id: '/producciones',
  path: '/producciones',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const FesmicaRoute = FesmicaRouteImport.update({
  id: '/fesmica',
  path: '/fesmica',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/fesmica': typeof FesmicaRoute
  '/nosotros': typeof NosotrosRoute
  '/producciones': typeof ProduccionesRoute
  '/talleres': typeof TalleresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/fesmica': typeof FesmicaRoute
  '/nosotros': typeof NosotrosRoute
  '/producciones': typeof ProduccionesRoute
  '/talleres': typeof TalleresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/fesmica': typeof FesmicaRoute
  '/nosotros': typeof NosotrosRoute
  '/producciones': typeof ProduccionesRoute
  '/talleres': typeof TalleresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/fesmica'
    | '/nosotros'
    | '/producciones'
    | '/talleres'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/fesmica'
    | '/nosotros'
    | '/producciones'
    | '/talleres'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/fesmica'
    | '/nosotros'
    | '/producciones'
    | '/talleres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  FesmicaRoute: typeof FesmicaRoute
  NosotrosRoute: typeof NosotrosRoute
  ProduccionesRoute: typeof ProduccionesRoute
  TalleresRoute: typeof TalleresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talleres': {
      id: '/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof TalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producciones': {
      id: '/producciones'
      path: '/producciones'
      fullPath: '/producciones'
      preLoaderRoute: typeof ProduccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fesmica': {
      id: '/fesmica'
      path: '/fesmica'
      fullPath: '/fesmica'
      preLoaderRoute: typeof FesmicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  FesmicaRoute: FesmicaRoute,
  NosotrosRoute: NosotrosRoute,
  ProduccionesRoute: ProduccionesRoute,
  TalleresRoute: TalleresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
