/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TalleresRouteImport } from './routes/talleres'
import { Route as ProduccionesRouteImport } from './routes/producciones'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LibroDeReclamacionesRouteImport } from './routes/libro-de-reclamaciones'
import { Route as FesmicaRouteImport } from './routes/fesmica'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as EncuestaRouteImport } from './routes/encuesta'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AliadosRouteImport } from './routes/aliados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminEncuestasRouteImport } from './routes/admin/encuestas'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TalleresRoute = TalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionesRoute = ProduccionesRouteImport.update({
  id: '/producciones',
  path: '/producciones',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LibroDeReclamacionesRoute = LibroDeReclamacionesRouteImport.update({
  id: '/libro-de-reclamaciones',
  path: '/libro-de-reclamaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FesmicaRoute = FesmicaRouteImport.update({
  id: '/fesmica',
  path: '/fesmica',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const EncuestaRoute = EncuestaRouteImport.update({
  id: '/encuesta',
  path: '/encuesta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AliadosRoute = AliadosRouteImport.update({
  id: '/aliados',
  path: '/aliados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEncuestasRoute = AdminEncuestasRouteImport.update({
  id: '/admin/encuestas',
  path: '/admin/encuestas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aliados': typeof AliadosRoute
  '/contacto': typeof ContactoRoute
  '/encuesta': typeof EncuestaRoute
  '/equipo': typeof EquipoRoute
  '/fesmica': typeof FesmicaRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/producciones': typeof ProduccionesRoute
  '/talleres': typeof TalleresRoute
  '/terminos': typeof TerminosRoute
  '/admin/encuestas': typeof AdminEncuestasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aliados': typeof AliadosRoute
  '/contacto': typeof ContactoRoute
  '/encuesta': typeof EncuestaRoute
  '/equipo': typeof EquipoRoute
  '/fesmica': typeof FesmicaRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/producciones': typeof ProduccionesRoute
  '/talleres': typeof TalleresRoute
  '/terminos': typeof TerminosRoute
  '/admin/encuestas': typeof AdminEncuestasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aliados': typeof AliadosRoute
  '/contacto': typeof ContactoRoute
  '/encuesta': typeof EncuestaRoute
  '/equipo': typeof EquipoRoute
  '/fesmica': typeof FesmicaRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/producciones': typeof ProduccionesRoute
  '/talleres': typeof TalleresRoute
  '/terminos': typeof TerminosRoute
  '/admin/encuestas': typeof AdminEncuestasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aliados'
    | '/contacto'
    | '/encuesta'
    | '/equipo'
    | '/fesmica'
    | '/libro-de-reclamaciones'
    | '/nosotros'
    | '/noticias'
    | '/producciones'
    | '/talleres'
    | '/terminos'
    | '/admin/encuestas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aliados'
    | '/contacto'
    | '/encuesta'
    | '/equipo'
    | '/fesmica'
    | '/libro-de-reclamaciones'
    | '/nosotros'
    | '/noticias'
    | '/producciones'
    | '/talleres'
    | '/terminos'
    | '/admin/encuestas'
  id:
    | '__root__'
    | '/'
    | '/aliados'
    | '/contacto'
    | '/encuesta'
    | '/equipo'
    | '/fesmica'
    | '/libro-de-reclamaciones'
    | '/nosotros'
    | '/noticias'
    | '/producciones'
    | '/talleres'
    | '/terminos'
    | '/admin/encuestas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliadosRoute: typeof AliadosRoute
  ContactoRoute: typeof ContactoRoute
  EncuestaRoute: typeof EncuestaRoute
  EquipoRoute: typeof EquipoRoute
  FesmicaRoute: typeof FesmicaRoute
  LibroDeReclamacionesRoute: typeof LibroDeReclamacionesRoute
  NosotrosRoute: typeof NosotrosRoute
  NoticiasRoute: typeof NoticiasRoute
  ProduccionesRoute: typeof ProduccionesRoute
  TalleresRoute: typeof TalleresRoute
  TerminosRoute: typeof TerminosRoute
  AdminEncuestasRoute: typeof AdminEncuestasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talleres': {
      id: '/talleres'
      path: '/talleres'
      fullPath: '/talleres'
      preLoaderRoute: typeof TalleresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producciones': {
      id: '/producciones'
      path: '/producciones'
      fullPath: '/producciones'
      preLoaderRoute: typeof ProduccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libro-de-reclamaciones': {
      id: '/libro-de-reclamaciones'
      path: '/libro-de-reclamaciones'
      fullPath: '/libro-de-reclamaciones'
      preLoaderRoute: typeof LibroDeReclamacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fesmica': {
      id: '/fesmica'
      path: '/fesmica'
      fullPath: '/fesmica'
      preLoaderRoute: typeof FesmicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encuesta': {
      id: '/encuesta'
      path: '/encuesta'
      fullPath: '/encuesta'
      preLoaderRoute: typeof EncuestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliados': {
      id: '/aliados'
      path: '/aliados'
      fullPath: '/aliados'
      preLoaderRoute: typeof AliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/encuestas': {
      id: '/admin/encuestas'
      path: '/admin/encuestas'
      fullPath: '/admin/encuestas'
      preLoaderRoute: typeof AdminEncuestasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliadosRoute: AliadosRoute,
  ContactoRoute: ContactoRoute,
  EncuestaRoute: EncuestaRoute,
  EquipoRoute: EquipoRoute,
  FesmicaRoute: FesmicaRoute,
  LibroDeReclamacionesRoute: LibroDeReclamacionesRoute,
  NosotrosRoute: NosotrosRoute,
  NoticiasRoute: NoticiasRoute,
  ProduccionesRoute: ProduccionesRoute,
  TalleresRoute: TalleresRoute,
  TerminosRoute: TerminosRoute,
  AdminEncuestasRoute: AdminEncuestasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
